languageCode: "en-us"
title: "Dirty Dozen Strava Results"
theme: "herring-cove"
baseURL: "mbarnes1.github.io/dirtydozen/"
#relativeURLs: True
publishDir: docs

params:
  ProfilePicture: "http://www.pointpark.edu/About/media/About/sunriseoverpittsburgh_dicello_685.jpg"
  links:
    Home: "/index"
    "2016": "/post/2016"
