languageCode: "en-us"
title: "Dirty Dozen Strava Results"
theme: "herring-cove"

params:
  ProfilePicture: "http://www.pointpark.edu/About/media/About/sunriseoverpittsburgh_dicello_685.jpg"
  links:
    Home: "/about"
    "2016": "/post/2016"
